;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="AI.Action.TryingDoor",DevComment="Персонаж пытается открыть дверь.")
GameplayTagList=(Tag="AI.Behavior.Exploring",DevComment="Персонаж занимается свободным осмотром местности")
GameplayTagList=(Tag="AI.Behavior.Interaction.LightSwitch",DevComment="Взаимодействие: Переключатель света")
GameplayTagList=(Tag="AI.Behavior.PathMovement",DevComment="Персонаж двигается по заданному массиву путевых точек")
GameplayTagList=(Tag="AI.Memories.Unknown",DevComment="Персонаж не знает статус выбранного объекта")
GameplayTagList=(Tag="Controller.CanMove",DevComment="")
GameplayTagList=(Tag="Game.PhaseFlag.NoInteractions",DevComment="Отключает все взаимодействия игрока с окружением")
GameplayTagList=(Tag="Level.Furn.Handle.TypeLocation",DevComment="")
GameplayTagList=(Tag="Level.Furn.Handle.TypeRotation",DevComment="")
GameplayTagList=(Tag="Movement.Trapped",DevComment="Указывает на объект, находящийся под влиянием ловушки")

